export const taskList = [
  {
    id: 0,
    name: "PartialJellyfinSync",
    title: "Recently Added Items Sync",
    description: "Pull newly added Jellyfin media, refresh recent shelves, and emit media-added webhooks.",
    type: "JOB",
    group: "Sync",
    link: "/api/startTask?task=PartialJellyfinSync",
  },
  {
    id: 1,
    name: "JellyfinSync",
    title: "Complete Jellyfin Sync",
    description: "Run the full Jellyfin library, user, season, episode, metadata, and stats refresh.",
    type: "JOB",
    group: "Sync",
    link: "/api/startTask?task=JellyfinSync",
  },
  {
    id: 2,
    name: "JellyfinPlaybackReportingPluginSync",
    title: "Playback Reporting Import",
    description: "Import Jellyfin Playback Reporting Plugin rows into JellyGlance activity.",
    type: "JOB",
    group: "Import",
    link: "/api/startTask?task=JellyfinPlaybackReportingPluginSync",
  },
  {
    id: 3,
    name: "Backup",
    title: "Backup JellyGlance",
    description: "Create a JellyGlance backup for app data, settings, and operational recovery.",
    type: "JOB",
    group: "Maintenance",
    link: "/api/startTask?task=Backup",
  },
  {
    id: 4,
    name: "RefreshDashboardStats",
    title: "Refresh Dashboard Stats",
    description: "Refresh PostgreSQL summary views used by home, libraries, users, and statistics.",
    type: "JOB",
    group: "Maintenance",
    link: "/api/startTask?task=RefreshDashboardStats",
  },
  {
    id: 5,
    name: "ClearStaleTasks",
    title: "Clear Stale Task Logs",
    description: "Mark orphaned running task logs as failed after restarts or interrupted jobs.",
    type: "JOB",
    group: "Maintenance",
    link: "/api/startTask?task=ClearStaleTasks",
  },
  {
    id: 6,
    name: "WebhookHealthCheck",
    title: "Webhook Health Check",
    description: "Send a task-completed test event through enabled task webhooks.",
    type: "JOB",
    group: "Webhooks",
    link: "/api/startTask?task=WebhookHealthCheck",
  },
  {
    id: 7,
    name: "IntegrationSync",
    title: "Integration Sync",
    description: "Refresh Arr calendar releases, download queues, integration status, and enabled webhooks.",
    type: "JOB",
    group: "Integrations",
    link: "/api/startTask?task=IntegrationSync",
  },
  {
    id: 8,
    name: "ArrCalendarSync",
    title: "Arr Calendar Sync",
    description: "Pull upcoming Sonarr, Radarr, and Lidarr releases into Calendar and emit calendar webhooks.",
    type: "JOB",
    group: "Integrations",
    link: "/api/startTask?task=ArrCalendarSync",
  },
  {
    id: 9,
    name: "DownloadQueueSync",
    title: "Download Queue Sync",
    description: "Refresh download client queue state for qBittorrent, Transmission, Deluge, SABnzbd, and NZBGet.",
    type: "JOB",
    group: "Downloads",
    link: "/api/startTask?task=DownloadQueueSync",
  },
  {
    id: 10,
    name: "IntegrationHealthCheck",
    title: "Integration Health Check",
    description: "Check connected Jellyfin, Arr apps, and download clients, then alert enabled health webhooks.",
    type: "JOB",
    group: "Integrations",
    link: "/api/startTask?task=IntegrationHealthCheck",
  },
];
